---
- name: Install clickhouse
  hosts: clickhouse
  roles:
    - ansible-clickhouse

- name: Install vector
  hosts: vector
  roles:
    - vector-role

- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: Nginx restart
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Install git for lighthouse
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Install epel-release for lighthouse
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install nginx for lighthouse
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Apply nginx config for lighthouse
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
  roles:
    - lighthouse-role
  post_tasks:
    - name: Apply lighthouse config
      become: true
      ansible.builtin.template:
        src: lighthouse_nginx.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: "0644"
      notify: Nginx restart
